// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: grpc-spec/match-judge.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_grpc_spec_match_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spec_match_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_spec_match_judge_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_grpc_spec_match_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_spec_match_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_spec_match_judge_proto_rawDescGZIP(), []int{1}
}

var File_grpc_spec_match_judge_proto protoreflect.FileDescriptor

const file_grpc_spec_match_judge_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpc-spec/match-judge.proto\x12\x03rpc\"B\n" +
	"\x12GetUserInfoRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"\x15\n" +
	"\x13GetUserInfoResponse2O\n" +
	"\vUserService\x12@\n" +
	"\vGetUserInfo\x12\x17.rpc.GetUserInfoRequest\x1a\x18.rpc.GetUserInfoResponseB\aZ\x05./rpcb\x06proto3"

var (
	file_grpc_spec_match_judge_proto_rawDescOnce sync.Once
	file_grpc_spec_match_judge_proto_rawDescData []byte
)

func file_grpc_spec_match_judge_proto_rawDescGZIP() []byte {
	file_grpc_spec_match_judge_proto_rawDescOnce.Do(func() {
		file_grpc_spec_match_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_spec_match_judge_proto_rawDesc), len(file_grpc_spec_match_judge_proto_rawDesc)))
	})
	return file_grpc_spec_match_judge_proto_rawDescData
}

var file_grpc_spec_match_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_spec_match_judge_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),  // 0: rpc.GetUserInfoRequest
	(*GetUserInfoResponse)(nil), // 1: rpc.GetUserInfoResponse
}
var file_grpc_spec_match_judge_proto_depIdxs = []int32{
	0, // 0: rpc.UserService.GetUserInfo:input_type -> rpc.GetUserInfoRequest
	1, // 1: rpc.UserService.GetUserInfo:output_type -> rpc.GetUserInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_spec_match_judge_proto_init() }
func file_grpc_spec_match_judge_proto_init() {
	if File_grpc_spec_match_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_spec_match_judge_proto_rawDesc), len(file_grpc_spec_match_judge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_spec_match_judge_proto_goTypes,
		DependencyIndexes: file_grpc_spec_match_judge_proto_depIdxs,
		MessageInfos:      file_grpc_spec_match_judge_proto_msgTypes,
	}.Build()
	File_grpc_spec_match_judge_proto = out.File
	file_grpc_spec_match_judge_proto_goTypes = nil
	file_grpc_spec_match_judge_proto_depIdxs = nil
}
