// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

const (
	AuthorizationScopes = "Authorization.Scopes"
)

// ErrorsDTO defines model for ErrorsDTO.
type ErrorsDTO struct {
	// Errors list of errors
	Errors []ErrorsDTO_Errors_Item `json:"errors"`
}

// ErrorsDTO_Errors_Item defines model for ErrorsDTO.errors.Item.
type ErrorsDTO_Errors_Item struct {
	// Code error code
	Code string `json:"code"`

	// Message error message
	Message              string                 `json:"message"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GoogleSignInRequestDTO defines model for GoogleSignInRequestDTO.
type GoogleSignInRequestDTO struct {
	// Code Google auth code
	Code string `json:"code"`
}

// GoogleSignInResponseDTO defines model for GoogleSignInResponseDTO.
type GoogleSignInResponseDTO struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
	User        struct {
		// Email user email
		Email string `json:"email"`

		// ProfileImageURL user profile image url
		ProfileImageURL *string `json:"profileImageURL"`

		// UserId user id
		UserId string `json:"userId"`

		// Username user name in app
		Username *string `json:"username"`
	} `json:"user"`
}

// RefreshAuthResponseDTO defines model for RefreshAuthResponseDTO.
type RefreshAuthResponseDTO struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
}

// SelfDTO defines model for SelfDTO.
type SelfDTO struct {
	// Email user email
	Email string `json:"email"`

	// ProfileImageURL user profile image url
	ProfileImageURL *string `json:"profileImageURL"`

	// UserId user id
	UserId string `json:"userId"`

	// Username user name in app
	Username *string `json:"username"`
}

// UserDTO defines model for UserDTO.
type UserDTO struct {
	// Email user email
	Email string `json:"email"`

	// ProfileImageURL user profile image url
	ProfileImageURL *string `json:"profileImageURL"`

	// UserId user id
	UserId string `json:"userId"`

	// Username user name in app
	Username *string `json:"username"`
}

// GoogleSignInJSONRequestBody defines body for GoogleSignIn for application/json ContentType.
type GoogleSignInJSONRequestBody = GoogleSignInRequestDTO

// Getter for additional properties for ErrorsDTO_Errors_Item. Returns the specified
// element and whether it was found
func (a ErrorsDTO_Errors_Item) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorsDTO_Errors_Item
func (a *ErrorsDTO_Errors_Item) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorsDTO_Errors_Item to handle AdditionalProperties
func (a *ErrorsDTO_Errors_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["message"]; found {
		err = json.Unmarshal(raw, &a.Message)
		if err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorsDTO_Errors_Item to handle AdditionalProperties
func (a ErrorsDTO_Errors_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["message"], err = json.Marshal(a.Message)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'message': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Refresh the user authentication state
	// (POST /refresh)
	RefreshAuthentication(c *gin.Context)
	// Get sensitive user info of access token owner
	// (GET /self)
	GetSelfInfo(c *gin.Context)
	// Google OAuth sign-in
	// (POST /signin/google)
	GoogleSignIn(c *gin.Context)
	// Revoke the refresh token and remove the cookie
	// (POST /signout)
	SignOut(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RefreshAuthentication operation middleware
func (siw *ServerInterfaceWrapper) RefreshAuthentication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshAuthentication(c)
}

// GetSelfInfo operation middleware
func (siw *ServerInterfaceWrapper) GetSelfInfo(c *gin.Context) {

	c.Set(AuthorizationScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSelfInfo(c)
}

// GoogleSignIn operation middleware
func (siw *ServerInterfaceWrapper) GoogleSignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GoogleSignIn(c)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignOut(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/refresh", wrapper.RefreshAuthentication)
	router.GET(options.BaseURL+"/self", wrapper.GetSelfInfo)
	router.POST(options.BaseURL+"/signin/google", wrapper.GoogleSignIn)
	router.POST(options.BaseURL+"/signout", wrapper.SignOut)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYUW/bNhD+KwQ3YC+K7K4dMPitW7rAQ7EUSdo9BEHASCeZjUQq5NGdV/i/D0dSsWxJ",
	"cRosWQbkzRWPvLvv7r7vmq8803WjFSi0fPaV22wBtfA/3xmjjT08O6Z/NEY3YFCCPwJ/RL9ysJmRDUqt",
	"+IxX0iLTBYvnCZcItbcTeS7JSFQfOi+hcZDsvJ3pHPov+xeZP0s4/CXqpgI+4/M/Pr19Pz+8/PX48B1P",
	"OK4a+mrRSFXydcJrsFaUo++1x90n3zpcaCP/FmTpPTJpmVRLUcm872OdcAM3ThrI+eycxwjbhy9u7fXV",
	"Z8iQYoofhDFi1bsfkRu6d6R1WcGpLNVcncCNA4uDxRkGMNxmwuGiD2PpDw/o8CAe3iPN/UHaRisLg1GK",
	"LANrz/Q1qH6wv/95xoIBQ28xUFpnwdDN7w0UfMa/m2waeRK7eHIKVUHed8PvOo8vDSVzAoUBu6COeMxc",
	"7ghuKKo2qf5U1kJW/QAoPRbOBmBsjC5kBfNalPDx5P3I9WjFJJkxZ+gp5apKXFH/hDEerNA8H3lxaJbC",
	"FSVqGLlER0wqJppmfwA7sMZoEt5CceurD8IQ7B8tmBfYnxz2OMqXG8l5kaL/XIraogTduLSyVFJdGrh5",
	"Zmo0Fqdt/p+C1OZjgjBdEkSPk843alIbmIWqeGHIp2RIAh8yZySuTqkIAfEt5qAPVyAMmN+0qQWGBuDJ",
	"TiI7DeFLSp7C1Q0oC8SGr8mxVIUOM65QZEg/A0b8dCGunZKE3LYTCoxZMEuZASu0YYcrh4L4GSX66Q8f",
	"mDd8+2HOE74EY8PtV+k0ndKjugElGsln/HU6TV8TUgIXPvVJHA7fhtpiv2KfiD4FgmW4ABbNQ95Uw0zr",
	"awkJM7DU12CZxIQJlTMD6IyyTDAFX7bGh241YlVpkafcB2c88NRj3SUSFMoslIRaIGyUPugfp69aIEH5",
	"kEXTVNF48tmGIoYp28cx4yThi7aNhXU+j8JV1aqFAnIPjNiKmFkUCOl43uuEv3mELKIKDYTuVCdCoAho",
	"FlxdC7Pa4O5T8TM6lA/1nSitp7jtAl3Qa5OWz0oY6KOT2BCZMwYUei8/kD4XmkmVVS6XqmQWlJUol8By",
	"gaLXHkeAJApzGqVeU0z/dTh9Qvv7AI2EJeRDqT2LSif8p0cAZzwCqZA4ufLURapFlukW+/LZeY93zy/W",
	"F92ePALs9EOQG+oWXWzPlf6iAuN2erPtSL/DTMJGM85xZ4Koq9xZszyPLW/pT2LK5kX4kNzyWx4IeGTQ",
	"IxUOcmaf/Lp/DuBB9sDiLzpf3aN4cSOMy30hXOVNl6JysFkt++uir9+3Vb6/yK63ZZqEfP0E8zmwqe6b",
	"VrKFnEmVPqxm6+RR5Ofhmbjm4Zm8eWJa8LPDYl+zK52vnp8Sxv9sHYfdS5bqQKq9widLpR2OE8xJ3I7u",
	"WKFisWq9jHZjLEH8cOywr39v+n6HGkY77GrC/am7syxQNgPJbFLoZHAneF4SyJP1irDzVwmdiYrlsIzR",
	"0LZvqrhU29lk4g0ORCPTQMNppuvZz9NX04nXAJKT6LoHTCgsu4WWluq4jrdFX1+s/wkAAP//9RwLbfEX",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
