// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ErrorsDTO defines model for ErrorsDTO.
type ErrorsDTO struct {
	// Errors list of errors
	Errors []ErrorsDTO_Errors_Item `json:"errors"`
}

// ErrorsDTO_Errors_Item defines model for ErrorsDTO.errors.Item.
type ErrorsDTO_Errors_Item struct {
	// Code error code
	Code string `json:"code"`

	// Message error message
	Message              string                 `json:"message"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GoogleSignInRequestDTO defines model for GoogleSignInRequestDTO.
type GoogleSignInRequestDTO struct {
	// Code Google auth code
	Code string `json:"code"`
}

// GoogleSignInResponseDTO defines model for GoogleSignInResponseDTO.
type GoogleSignInResponseDTO struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
	User        struct {
		// Email user email
		Email string `json:"email"`

		// ProfileImageUrl user profile image url
		ProfileImageUrl *string `json:"profileImageUrl"`

		// UserId user id
		UserId string `json:"user_id"`

		// Username user name in app
		Username *string `json:"username"`
	} `json:"user"`
}

// RefreshAuthResponseDTO defines model for RefreshAuthResponseDTO.
type RefreshAuthResponseDTO struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
}

// UserDTO defines model for UserDTO.
type UserDTO struct {
	// Email user email
	Email string `json:"email"`

	// ProfileImageUrl user profile image url
	ProfileImageUrl *string `json:"profileImageUrl"`

	// UserId user id
	UserId string `json:"user_id"`

	// Username user name in app
	Username *string `json:"username"`
}

// GoogleSignInJSONRequestBody defines body for GoogleSignIn for application/json ContentType.
type GoogleSignInJSONRequestBody = GoogleSignInRequestDTO

// Getter for additional properties for ErrorsDTO_Errors_Item. Returns the specified
// element and whether it was found
func (a ErrorsDTO_Errors_Item) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorsDTO_Errors_Item
func (a *ErrorsDTO_Errors_Item) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorsDTO_Errors_Item to handle AdditionalProperties
func (a *ErrorsDTO_Errors_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["message"]; found {
		err = json.Unmarshal(raw, &a.Message)
		if err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorsDTO_Errors_Item to handle AdditionalProperties
func (a ErrorsDTO_Errors_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["message"], err = json.Marshal(a.Message)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'message': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Refresh the user authentication state
	// (POST /refresh)
	RefreshAuthentication(c *gin.Context)
	// Google OAuth sign-in
	// (POST /signin/google)
	GoogleSignIn(c *gin.Context)
	// Revoke the refresh token and remove the cookie
	// (POST /signout)
	SignOut(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RefreshAuthentication operation middleware
func (siw *ServerInterfaceWrapper) RefreshAuthentication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshAuthentication(c)
}

// GoogleSignIn operation middleware
func (siw *ServerInterfaceWrapper) GoogleSignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GoogleSignIn(c)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignOut(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/refresh", wrapper.RefreshAuthentication)
	router.POST(options.BaseURL+"/signin/google", wrapper.GoogleSignIn)
	router.POST(options.BaseURL+"/signout", wrapper.SignOut)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXTW/jNhD9KwTboyI53RQofEubReGiaBbZ7PZQBAYjjWWuJZLhh1t3of9eDEn5i1KS",
	"DWo0BfZma4bDmTdv3kifaSlbJQUIa+j0MzXlElrmf77VWmpzdXuNf5SWCrTl4E3gTfirAlNqriyXgk5p",
	"w40lckGiPaPcQuv9WFVxdGLNu71IVjvIjmKXsoI0so9IvC2j8BdrVQN0Sme/fbz8dXY1/+n66i3NqN0o",
	"fGqs5qKmXUZbMIbVo/F6837IS2eXUvO/GXr6Gwk3hIs1a3iV3tFlVMOD4xoqOv2Dxgz7wHdbf3n/CUqL",
	"OcUHTGu2Sc5H5IbO/Sxl3cB7XouZuIEHB8YONmcYwHCaMGeXKYy1N56h8Swan1Hm00kaJYWBwSxZWYIx",
	"t3IFIk32l99vSXAg1nsMtNYZ0HjyWw0LOqXfFDsiF5HFxQcDGm8/Tn//8hhpqJgbWGgwS2TEKWt5JLmh",
	"rPqi0qlsGW/SBLA8EmwDMCotF7yBWctq+KDHjkcvwtGNOI2hhGsado/8CWM82KE5r0ZCDg1TOCNYCyOH",
	"0ES4IEyppzM4wrVPJ6M9GIKXK39ZCsMQ8JFV8536fVXF/1wV+6YECZsbXgsu5hoeXpkwjuVp1P9TG/t6",
	"dNDIOUJ0mnK+SB7Rm4uFDP0WlpUWfwZJoe+XbOUEx/wPs0B6EwN6zUsgC6nJ1cZZhrNqufVMCA+Id7x8",
	"N6MZXYM24fR5PsknGFQqEExxOqVv8kn+BnWF2aUHoYhAeXiksSkSH3GUmAVD7BJIdA+goOSVUq44ZETD",
	"Wq7AEG4zwkRFNFinhSGMCPjzAEo8pdimkazKqU9O+/GdVXS6v9tAWF56C0Wow6LzSX83Oe+BBOFTZko1",
	"0bn4ZKTYvTM+xbdxwvimHWJhnK9j4Zpm00MBlQeGHWRMjGUW8vG6u4xenKCKqEgDqTuxlyFgBjgtrm2Z",
	"3uxw96X4lTZUD/KO1cbT/bBBdxitCOpRBC0ZZ9QtQ6LURwLnWbPeko3bnMwW4UG2ZVMV6D4CayTeIENT",
	"qu2/E9IwzGDsj7LaPKMtUYvjWl0w13jXNWsc7EQ9FWrfmS/rabpCukPxwcXcJSMy+dfJNbAjnpoR9IWK",
	"cJG/rGdddpJhf3klTr28kosT9GR84ONLEIm8Jvey2rw+3YmvOddh0/FanHHxHJmRzo4LzE3cRY8srNis",
	"Vq6j35hKoD5cO5uuoIv03iHCSGc96t+H5h/3yOJ3ReN3PH4OIYypNGM1A8XsStir4FHwMK6/Ce3J94As",
	"WUMqWMds8DULv7zo0lplpkXhHc6Y4nmQ4byU7fSHyfmkwJtod7e9OgEmNJZsocVXmPjy0ze9u+v+CQAA",
	"//8AtYhm9hEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
