// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ErrorsDTO defines model for ErrorsDTO.
type ErrorsDTO struct {
	// Errors list of errors
	Errors []ErrorsDTO_Errors_Item `json:"errors"`
}

// ErrorsDTO_Errors_Item defines model for ErrorsDTO.errors.Item.
type ErrorsDTO_Errors_Item struct {
	// Code error code
	Code string `json:"code"`

	// Message error message
	Message              string                 `json:"message"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// GoogleSignInRequestDTO defines model for GoogleSignInRequestDTO.
type GoogleSignInRequestDTO struct {
	// Code Google auth code
	Code string `json:"code"`
}

// GoogleSignInResponseDTO defines model for GoogleSignInResponseDTO.
type GoogleSignInResponseDTO struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
	User        struct {
		// Email user email
		Email string `json:"email"`

		// Nickname user nickname
		Nickname string `json:"nickname"`

		// ProfileImageUrl user profile image url
		ProfileImageUrl string `json:"profileImageUrl"`

		// UserId user id
		UserId string `json:"user_id"`
	} `json:"user"`
}

// RefreshAuthResponseDTO defines model for RefreshAuthResponseDTO.
type RefreshAuthResponseDTO struct {
	// AccessToken JWT access token
	AccessToken string `json:"accessToken"`
}

// UserDTO defines model for UserDTO.
type UserDTO struct {
	// Email user email
	Email string `json:"email"`

	// Nickname user nickname
	Nickname string `json:"nickname"`

	// ProfileImageUrl user profile image url
	ProfileImageUrl string `json:"profileImageUrl"`

	// UserId user id
	UserId string `json:"user_id"`
}

// GoogleSignInJSONRequestBody defines body for GoogleSignIn for application/json ContentType.
type GoogleSignInJSONRequestBody = GoogleSignInRequestDTO

// Getter for additional properties for ErrorsDTO_Errors_Item. Returns the specified
// element and whether it was found
func (a ErrorsDTO_Errors_Item) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ErrorsDTO_Errors_Item
func (a *ErrorsDTO_Errors_Item) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ErrorsDTO_Errors_Item to handle AdditionalProperties
func (a *ErrorsDTO_Errors_Item) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["message"]; found {
		err = json.Unmarshal(raw, &a.Message)
		if err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ErrorsDTO_Errors_Item to handle AdditionalProperties
func (a ErrorsDTO_Errors_Item) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["message"], err = json.Marshal(a.Message)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'message': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Refresh the user authentication state
	// (POST /refresh)
	RefreshAuthentication(c *gin.Context)
	// Google OAuth sign-in
	// (POST /signin/google)
	GoogleSignIn(c *gin.Context)
	// Revoke the refresh token and remove the cookie
	// (POST /signout)
	SignOut(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RefreshAuthentication operation middleware
func (siw *ServerInterfaceWrapper) RefreshAuthentication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshAuthentication(c)
}

// GoogleSignIn operation middleware
func (siw *ServerInterfaceWrapper) GoogleSignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GoogleSignIn(c)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignOut(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/refresh", wrapper.RefreshAuthentication)
	router.POST(options.BaseURL+"/signin/google", wrapper.GoogleSignIn)
	router.POST(options.BaseURL+"/signout", wrapper.SignOut)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xX32/cNgz+VwRtj459WTNguLdsKYYbhqVI0+5hCA6qTfvU2JIjUbfdCv/vAyX5ftlO",
	"0mCHdUDfEpOiyI8fP+o+8Vw3rVag0PL5J27zFTTC//naGG3s1e01/dMa3YJBCd4E3kR/FWBzI1uUWvE5",
	"r6VFpksW7QmXCI33E0UhyUnUb/YioXGQHMXOdQHDyD4i87aEw1+iaWvgc7747f3lr4ur5U/XV695wnHT",
	"0leLRqqKdwlvwFpRTcbrzfshLx2utJF/C/L0NzJpmVRrUctieEeXcAMPThoo+PwPHjPsA99t/fWHj5Aj",
	"5RQ/CGPEZnA+Ijd27metqxreykot1A08OLA42pxxAMNpJhyuhjBW3nhGxrNofEaZTydpW60sjGYp8hys",
	"vdX3oIbJ/vL7LQsODL3HSGudBUMnvzVQ8jn/JtsROYsszt5ZMHT7cfr7l8dIY8XcQGnArogRp6zlkeTG",
	"suqLGk5lI2Q9TIDKY8E2AqOS+b0SDUyc25pHjrZGl7KGRSMqeGembo5eTJIbc6aeauZSFhMhnjF3fYCE",
	"95XuZX6c6BiqkTLLnbR9lbz/XPL6pgR9WlpZKamWBh6+MNWbytO2/0/h6+sxQQCXBNFpyvks7SNvqUod",
	"+q1Q5Eh/Bvnib1fi3ilJ+R9mQfRmFsxa5sBKbdjVxqGgWUWJngnhA/OOl28WPOFrMDacPk9n6YyC6haU",
	"aCWf81fpLH1FuiJw5UHIIlAeHm1xiMR7GiWBYBmugEX3AAqTNHP6XkLCDKz1PVgmMWFCFcwAOqMsE0zB",
	"nwdQ0qlWbGotipT75Iwf30XB5/uLCxTK3Fs4QR22mE/6u9l5DyQon7Jo2zo6Zx+tVrsH4VN8myaMb9oh",
	"Ftb5OkpX15seCig8MOIgY2ZRIKTTdXcJvzhBFVGRRlJ3ai9DoAxoWlzTCLPZ4e5L8ZtrrB7inaisp/th",
	"g+4oWhbUIwtaMs2oW0FEqY4EzrNmvSWbxJQtyvAh2bKpCHSfgDUSb5ShQ6rtP/h4GGaw+KMuNs9oS9Ti",
	"uFZL4Wrvuha1g52oD4Xad+bzejpcId2h+NBi7gYjMvvXyTWyI56aEfKFgkmVvqxnXXKSYX95Ja59eSUX",
	"J+jJ9MDHRxCLvGYfdLH58nQnPnOuw6aTlTqT6jkyox1OC8xN3EWPLKzYrEavo9+USpA+XDscrqCL4b1j",
	"hNEOPerfh+Yf9wjBKFH7HU+/dQjGoTRTNSPF7ErYq+BR8Ciuv4nsg98DOhc1K2Ads6FnFv024ivE1s6z",
	"zDuciVamQYbTXDfzH2bns4xu4t3d9uoBMKGxbAstPWHi46dvenfX/RMAAP//GZgkHdMRAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
