root = "."
tmp_dir = "tmp"

[build]
cmd = "/bin/dlv exec --listen=:2345 --headless=true --api-version=2 --accept-multiclient --log ./app/server --continue
bin = "app/server"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
delay = 500
rebuild_interval = 500

[color]
main = "yellow"6