// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuthUser struct {
	ID              int64
	Code            string
	GoogleID        string
	Email           string
	ProfileImageUrl sql.NullString
	Username        sql.NullString
	SignedUpAt      time.Time
	DeletedAt       sql.NullTime
}

type AuthUserRefreshToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type AuthUserSnapshot struct {
	ID              int64
	UserID          int64
	Email           string
	ProfileImageUrl sql.NullString
	Username        sql.NullString
	CreatedAt       time.Time
}
