// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthUser struct {
	ID              int64
	Code            string
	GoogleID        string
	Email           string
	ProfileImageUrl pgtype.Text
	Username        pgtype.Text
	SignedUpAt      pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type AuthUserRefreshToken struct {
	ID        int64
	UserID    int64
	TokenHash string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type AuthUserSnapshot struct {
	ID              int64
	UserID          int64
	Email           string
	ProfileImageUrl pgtype.Text
	Username        pgtype.Text
	CreatedAt       pgtype.Timestamptz
}
