CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE auth.user_refresh_tokens ( -- refresh tokens for Dyutas users
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    token_hash varchar(255) NOT NULL,
    created_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz NULL -- when the refresh token is revoked
);
CREATE UNIQUE INDEX idx_user_refresh_tokens_user_id_token_hash_for_token_lookup ON auth.user_refresh_tokens(user_id, token_hash);
CREATE INDEX idx_user_refresh_tokens_user_id_expires_at_for_revocation ON auth.user_refresh_tokens(user_id, expires_at);
CREATE INDEX idx_user_refresh_tokens_expires_at_for_cleanup ON auth.user_refresh_tokens(expires_at);